name: githubdummy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependency_overrides:
  http: ^1.2.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  provider: ^6.1.2
  http: ^1.2.1
  infinite_scroll_pagination: ^4.0.0
  get_it: ^7.7.0
  go_router: ^14.0.1
  flutter_svg: ^2.0.10+1
  flutter_octicons: ^0.43.0
  intl: ^0.19.0
  dio: ^5.4.3+1
  url_launcher: ^6.2.6
  url_launcher_web: ^2.3.1
  auth0_flutter: ^1.7.2
  flutter_web_auth_2: ^2.2.1
  github: ^9.24.0
  oauth2_client: ^3.2.2
  shared_preferences: ^2.2.3
  get_storage: ^2.1.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0


flutter:

  uses-material-design: true

  assets:
    - assets/logo/github-mark/
    - assets/images/


  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
        - asset: assets/fonts/SFProDisplay-Bold.ttf
          weight: 700
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf
        - asset: assets/fonts/SFProText-Bold.ttf
          weight: 700
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 600

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
